CREATE OR REPLACE FUNCTION MOCKSTG."UNMASK_DATA" (p_text IN VARCHAR2) RETURN VARCHAR2 IS
    V_RET_STR VARCHAR2(200);
    V_TRANSLATE_INP VARCHAR2(200) := 'STUVYZABCDEFGHIJKLMNOPQRWX6789012345stuvyzabcdefghijklmnopqrwx ';
    V_TRANSLATE_OUT VARCHAR2(200) := 'ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890abcdefghijklmnopqrstuvwxyz ';
BEGIN
    V_RET_STR := TRANSLATE(p_text,V_TRANSLATE_INP,V_TRANSLATE_OUT);
    RETURN V_RET_STR;
END;
