CREATE TABLE RET_VALID_CIF nologging
AS
SELECT INDCLIENT_CODE ORGKEY
    ,INDCLIENT_FIRST_NAME CUST_FIRST_NAME
	,INDCLIENT_MIDDLE_NAME CUST_MIDDLE_NAME
	,INDCLIENT_LAST_NAME CUST_LAST_NAME
	,INDCLIENT_SUR_NAME CUST_SUR_NAME
	,INDCLIENT_MOTHER_MAID_NAME MAIDENNAMEOFMOTHER
	,INDCLIENT_FATHER_NAME STRUSERFIELD1
	,SUBSTR(CLIENTS_NAME,0,50) PREFERREDNAME
	,SUBSTR(INDCLIENT_FIRST_NAME,0,10) SHORT_NAME
	,INDCLIENT_BIRTH_DATE CUST_DOB
    ,INDCLIENT_SEX GENDER
    ,INDCLIENT_NATNL_CODE NATIONALITY_CODE
    ,INDCLIENT_EMPLOYEE_NUM STAFFEMPLOYEEID
    ,INDCLIENT_LANG_CODE CUST_LANGUAGE
    ,INDCLIENT_OCCUPN_CODE OCCUPATION_CODE
    ,INDCLIENT_BIRTH_PLACE_CODE PLACEOFBIRTH
    ,INDCLIENT_RELIGN_CODE CUST_COMMUNITY
    ,INDCLIENT_DISABLED PHYSICAL_STATE
    ,DECODE(INDCLIENT_RESIDENT_STATUS,'N','Y','N') CUSTOMERNREFLAG
    ,CLIENTS_TITLE_CODE SALUTATION_CODE
    ,LPAD(CLIENTS_HOME_BRN_CODE,4,'0') PRIMARY_SOL_ID
    ,NVL(CLIENTS_OPENING_DATE,CLIENTS_ENTD_ON) RELATIONSHIPOPENINGDATE
    ,TRIM(CLIENTS_ARM_CODE) MANAGER
    ,CLIENTS_RISK_CATEGORIZATION RISKRATING
    ,CLIENTS_SEGMENT_CODE SEGMENTATION_CLASS
    ,CLIENTS_CUST_CATG CUST_TYPE_CODE
    ,CLIENTS_CONST_CODE CONSTITUTION_REF_CODE
    ,CLIENTS_IT_STAT_CODE IT_STAT_CODE
    ,CLIENTS_IT_SUB_STAT_CODE IT_SUB_STAT_CODE
	,DECODE(INDCLIENTSFATCA_REQD,'0','N','1','Y') ForeignAccTaxReportingReq
	,CLNTSTATMRK_STATUS STATUS_CODE
	,CLNTSTATMRK_EFFDATE STATUS_DATE
	,FORM15REC_TAX_REGIME TAXREGIME
	,TSSCR_CKYC_NUMBER
	,CKYCHDTL_CKYC_NUM
	,CLIENTS_HOME_BRN_CODE SOL_ID
	,CLIENTS_ADDR_INV_NUM ADDR_INV_NUM
	,INDCLIENT_PID_INV_NUM PID_INV_NUM
	,INDCLIENT_MARITAL_STATUS MARITAL_STATUS_CODE
	,INDCLIENT_EMPLOY_TYPE EMPLOYMENT_STATUS
	,INDCLIENT_CASTE_CODE CUSTCASTE
	,INDCLIENT_ANNUAL_INCOME_SLAB ANNUAL_SALARY_INCOME
	,INDCLIENT_NATNL_CODE NATIONALITY
FROM cbs.clients A
join CBS.INDCLIENTS B ON B.INDCLIENT_CODE = A.clients_code
LEFT JOIN CBS.indclientsfatca C ON C.INDCLIENTSFATCA_CLIENTCODE = A.clients_code
LEFT JOIN (
	SELECT CLNTSTATMRK_CUSTNUM, CLNTSTATMRK_STATUS, CLNTSTATMRK_EFFDATE,
		   ROW_NUMBER() OVER(PARTITION BY CLNTSTATMRK_CUSTNUM ORDER BY CLNTSTATMRK_EFFDATE DESC) as rn
	FROM CBS.CLNTSTATMRK
) stat ON stat.CLNTSTATMRK_CUSTNUM = a.clients_code AND stat.rn = 1
LEFT JOIN (
	SELECT FORM15REC_CLIENT_NUM, FORM15REC_TAX_REGIME
	FROM CBS.FORM15RECV
	WHERE SYSDATE BETWEEN FORM15REC_FORM_DATE AND FORM15REC_VALID_UPTO
	  AND FORM15REC_FIN_YEAR = EXTRACT(YEAR FROM UTK_FN_GET_CURR_FIN_YR_END_DT)
) f15 ON f15.FORM15REC_CLIENT_NUM = A.clients_code 
LEFT JOIN (
	SELECT TSSCR_CLIENT_ID, TSSCR_CKYC_NUMBER
	FROM (
		SELECT t.TSSCR_CLIENT_ID, t.TSSCR_CKYC_NUMBER,
			   ROW_NUMBER() OVER(PARTITION BY t.TSSCR_CLIENT_ID ORDER BY t.TSSCR_PROCESSED_ON DESC, t.TSSCR_REC_SL DESC) as rn
		FROM CBS.TSSCKCYCBSRESPONSE t
	) WHERE rn = 1
) kyc1 ON kyc1.TSSCR_CLIENT_ID = A.clients_code
-- Inline view for the latest CKYC number from the second source
LEFT JOIN (
	SELECT CKYCHDTL_CLIENT_CD, CKYCHDTL_CKYC_NUM
	FROM (
		SELECT h.CKYCHDTL_CLIENT_CD, h.CKYCHDTL_CKYC_NUM,
			   ROW_NUMBER() OVER(PARTITION BY h.CKYCHDTL_CLIENT_CD, h.CKYCHDTL_ENTITY ORDER BY h.CKYCHDTL_PROC_DATE DESC) as rn
		FROM CBS.CKYCHEADERDTL h WHERE h.CKYCHDTL_ENTITY = '1'
	) WHERE rn = 1
) kyc2 ON kyc2.CKYCHDTL_CLIENT_CD = A.clients_code
;

CREATE INDEX IDX_RET_VALID_CIF ON RET_VALID_CIF(SOL_ID) NOLOGGING PARALLEL 30;
CREATE INDEX IDX_RET_VALID_CIF1 ON RET_VALID_CIF(ORGKEY,ADDR_INV_NUM) NOLOGGING PARALLEL 30;
CREATE INDEX IDX_RET_VALID_CIF2 ON RET_VALID_CIF(ORGKEY,PID_INV_NUM) NOLOGGING PARALLEL 30;
CREATE INDEX IDX_RET_VALID_CIF3 ON RET_VALID_CIF(ORGKEY) NOLOGGING PARALLEL 30;
